### ISSUE TITLE
Refactoring: Update Slate to 0.82

### ISSUE THREAD

**Issue by sesa929** [serlo/backlog#10]
## Description

In https://github.com/edtr-io/edtr-io we need to update `slate` to the most recent version which includes many breaking changes. Thus we need to rewrite the text plugin.

Fixed by https://github.com/edtr-io/edtr-io/pull/398

## ToDos

- [x] #54
- [ ] #67
- [x] #68 
- [ ] #98
- [x] #55
- [x] #56
- [x] #57
- [x] #58
- [x] #59
- [x] #60
- [x] #61 
- [x] #81
- [x] #85
- [x] #87
- [x] Make sure the placeholder is shown for an empty text editor (+ rename typography util to richText)
- [x] #88
- [ ] #92
- [x] Finalize controls: 
![2022-10-13-141909_354x116_scrot](https://user-images.githubusercontent.com/1327215/195594267-4a12c239-b283-495a-b349-d302d7e7eb59.png)
  - [x] bold
  - [x] italic
  - [x] link
  - [x] heading
  - [x] list
    - [ ] bug when a selection is completely inside a block
  - [x] function 
  - [x] code
- [x] keyboard shortcuts
  - [x] `Strg + I`: italic
  - [x] `Strg + B`: bold 
  - [x] `Strg + K`: Create link
- [x] Markdown-Kürzel:
  - Add `*` in new line creates a list after pressing space (as in Google-Doc)
  - Add `##` in new paragraph + space creates a header

# Questions to Jonas
- [x] Why does math element have children in your implementation? -> Slate requires to always render the `props.children` (see https://docs.slatejs.org/concepts/09-rendering)
 
## Open questions: Do we still need these features?

- [ ] Bottom toolbar (visible when cursor does not move for a time and there is no selection range) -> Follow-Up?!
- [ ] Add links in paragraph creates a link (as in Google-Doc)
  - Does not seem to work at serlo.org...
- [ ] Blockquote
  - [ ] Do we still need the blockquote in edtr-io?! At Serlo we do not use it any more...
- [ ] Drag&Drop of files (from file browser) creates a image plugin -> Follow-Up Issue

**Comment by kulla** [comment]
Fixed by https://github.com/edtr-io/edtr-io/pull/398

# ToDo

- [ ] [plugin suggestion](https://github.com/edtr-io/edtr-io/blob/39c98d319dfa6e2c967b7d53763c3d3d28163e4e/packages/plugins/text/src/plugins/plugin-suggestions.tsx) "/"
- [ ] math editing
    - [ ] using arrow keys to step in /out of formula not working)
    - [ ] bug: toolbar is not showing when selection starts inside a math element
- [ ] "Enter" character -> new plugin
- [ ] Save Selection in state
- [ ] Refactoring
- [ ] Support for Placeholder + config of it
- [ ] Possibility to reduce number of allowed text plugins per configuration: 
![2022-10-13-142330_157x118_scrot](https://user-images.githubusercontent.com/1327215/195595119-29a37228-e6c7-4d26-baec-cb2bc9f178bf.png)
- [ ] Finalize controls: 
![2022-10-13-141909_354x116_scrot](https://user-images.githubusercontent.com/1327215/195594267-4a12c239-b283-495a-b349-d302d7e7eb59.png)
  - [x] bold
  - [x] italic
  - [x] link
  - [x] heading
  - [x] list
    - [ ] bug when a selection is completely inside a block
  - [x] function 
  - [x] code
- [x] keyboard shortcuts
  - [x] `Strg + I`: italic
  - [x] `Strg + B`: bold 
  - [x] `Strg + K`: Create link
- [x] Markdown-Kürzel:
  - Add `*` in new line creates a list after pressing space (as in Google-Doc)
  - Add `##` in new paragraph + space creates a header

# Questions to Jonas
- [x] Why does math element have children in your implementation? -> Slate requires to always render the `props.children` (see https://docs.slatejs.org/concepts/09-rendering)
 
# Do we still need this?!

- [ ] Bottom toolbar (visible when cursor does not move for a time and there is no selection range) -> Follow-Up?!
- [ ] Add links in paragraph creates a link (as in Google-Doc)
  - Does not seem to work at serlo.org...
- [ ] Blockquote
  - [ ] Do we still need the blockquote in edtr-io?! At Serlo we do not use it any more...
- [ ] Drag&Drop of files (from file browser) creates a image plugin -> Follow-Up Issue

**Comment by sesa929** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactoring: Update Slate to 0.82](https://trello.com/c/2dL76u8l/61-refactoring-update-slate-to-082)

**Comment by kulla** [comment]
Issues of label `Upgrade slate` (because I want to delete this label): 
![2023-05-08-181745_1122x890_scrot](https://user-images.githubusercontent.com/1327215/236876225-0e69ba11-57e5-4074-9311-da6d05ead855.png)
