### ISSUE TITLE
Improve AMB

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#113]
- [x] https://github.com/dini-ag-kim/amb/issues/223
- [x] https://github.com/dini-ag-kim/amb/issues/207
- [x] https://github.com/dini-ag-kim/amb/issues/215
- [x] https://github.com/dini-ag-kim/amb/issues/218
- [x] https://github.com/dini-ag-kim/amb/issues/219
- [x] https://github.com/dini-ag-kim/amb/issues/220
- [ ] https://github.com/dini-ag-kim/amb/issues/204
- [x] https://github.com/dini-ag-kim/amb/issues/200
- [x] https://github.com/dini-ag-kim/amb/issues/199
- [x] https://github.com/dini-ag-kim/amb/issues/194
- [x] https://github.com/dini-ag-kim/amb/issues/192
- [x] https://github.com/dini-ag-kim/amb/issues/190
- [x] https://github.com/dini-ag-kim/amb/issues/129
- [x] https://github.com/dini-ag-kim/amb/issues/216
- [x] https://github.com/dini-ag-kim/amb/issues/212
- [x] https://github.com/dini-ag-kim/amb/issues/211
- [x] https://github.com/dini-ag-kim/amb/issues/210
- [x] https://github.com/dini-ag-kim/amb/issues/208
- [x] https://github.com/dini-ag-kim/amb/issues/205
- [x] https://github.com/dini-ag-kim/amb/issues/202
- [x] https://github.com/dini-ag-kim/amb/issues/197
- [x] https://github.com/dini-ag-kim/amb/issues/195
- [x] https://github.com/dini-ag-kim/amb/issues/193
- [x] https://github.com/dini-ag-kim/amb/issues/191

**Comment by kulla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allgemeines Metadatenprofil für Bildungsressourcen verbessern](https://trello.com/c/QnVRObJs/143-allgemeines-metadatenprofil-f%C3%BCr-bildungsressourcen-verbessern)

**Comment by kulla** [comment]
Mainly done. This tracking issue is not needed any more. https://github.com/dini-ag-kim/amb/milestone/1 is a better overview...
