### ISSUE TITLE
Define Editor UX issues (especially: help links and visibility of settings)

### ISSUE THREAD

**Issue by sesa929** [serlo/backlog#13]
![](https://github.trello.services/images/mini-trello-icon.png) [M2.10 Verbesserungen an der UX/UI des Editors sind live (mindestens 8 weitere bestehende Lerninhalte verbessert)](https://trello.com/c/J1oT90Hv/36-m210-verbesserungen-an-der-ux-ui-des-editors-sind-live-mindestens-8-weitere-bestehende-lerninhalte-verbessert)

As author i can use the serlo editor in an intuitive way

## Overview
https://miro.com/app/board/uXjVP0cDuaI=/

## TODOs

- [x] Meeting Gregor, Botho, Sebastian, Quinn
- [ ] #30 
- [ ] Tab Management
- [ ] Selection and Copy Paste
- [ ] Settings: Position and visibility
- [ ] Help / Helpful info for authors
- [ ] Consistent style of interactive elements
- [ ] …

-- 

- [ ] Which refactorings do we need for editor framework?
  - [ ] Shall store action dispatching be synchronous?
    - Example: Equations-Plugin + Focus Managenent -> When you add a new equation in the `props.state` you still have the old state after the dispatch (dispatch is asynchronous due to redux-saga)
- [ ] What are the pain points in creating plugins?

**Comment by kulla** [comment]
Useful resource: https://docs.google.com/document/d/1UxLXhYNMqrtPJHTsm42ojfPD9xFik3egPvQ4QWJH42o/edit

**Comment by GregorZupan** [comment]
Quick UX evaluation of first impressions of Editor (running document)

https://lizard-toque-3ec.notion.site/Serlo-Editor-UX-Evaluation-Issues-706ef5eae5c24d9a94c2a90b65459a70

**Comment by elbotho** [comment]
Half of the TODOs here are DX or refactoring unrelated to UX imho.

**Comment by sesa929** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [M2.10 Verbesserungen an der UX/UI des Editors sind live (mindestens 8 weitere bestehende Lerninhalte verbessert)](https://trello.com/c/J1oT90Hv/36-m210-verbesserungen-an-der-ux-ui-des-editors-sind-live-mindestens-8-weitere-bestehende-lerninhalte-verbessert)
