### ISSUE TITLE
Consolidate all plugins in frontend / edtr-io in one repository

### ISSUE THREAD

**Issue by sesa929** [serlo/backlog#16]
# Background

The editor code moved into our frontend repository. The RLP integration still uses the editor code from the (now deprecated) edtr-io repository. The goal is, the RLP integration should use the editor code from frontend. With this change, all improvements and bugfixes done to the editor (implemented in frontend repo) will be available to both serlo.org and the RLP integration with minimal effort.

# Acceptance criteria

The RLP integration does not depend on edtr-io repository any more and imports all editor code from frontend repository.

# Subtasks

- [x] #100 
- [x] #130 
- [x] #131
- [x] Make box use correct registry
- [x] Get table plugin to work
- [x] #144 
- [x] Get equations plugin to work
- [x] #146
- [x] Re-enable tailwind "serlo-" autocomplete
- [x] Test if using tailwind preset in frontend broke some styling on serlo.org
- [x] #150
- [x] Fix: No-edit view can be edited
- [x] Fix broken docker build
- [x] Remove box label "⚠️ Boxen ohne Inhalt werden nicht angezeigt" in no-edit view when there is content
- [x] Make github workflows clone git submodule as well
- [x] Remove dep/frontend/node_modules and add dependencies in the outermost scope. This might help with tsc issues. 
- [x] Fix docker run error
- [x] Clean up dockerfile
- [x] Merge pull request
- [x] Write documentation 

# Potential followups

- [ ] Re-add edu-sharing specific tailwind theming
- [ ] Stop using component `Renderer` and use similar approach as in frontend repo
- [ ] Archive “edtr-io” packages + repositories + website
- [ ] Move localized strings into plugins (loggedInData)?  
- [ ] Create icon for edusharing plugin in menu
- [x] Why does tailwind put classes in both generated styles.css and serlo-tailwind.css?
- [x] Fix: Injected serlo content is cut off when too long
- [x] Change imports `@edtr-io/...` to `@frontend/...`
- [ ] Use injection plugin from `frontend`

**Comment by sesa929** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Consolidate all plugins in frontend / edtr-io in one repository](https://trello.com/c/1LEO1acy/62-consolidate-all-plugins-in-frontend-edtr-io-in-one-repository)

**Comment by kulla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Serlo Editor: Konsolidierung des Codes in einem Repo (Blocker für Durchführung UX/UI-Verbesserungen)](https://trello.com/c/wLCgAHMF/81-serlo-editor-konsolidierung-des-codes-in-einem-repo-blocker-f%C3%BCr-durchf%C3%BChrung-ux-ui-verbesserungen)

**Comment by LarsTheGlidingSquirrel** [comment]
<details>
<summary>Outdated issue description</summary>
Currently (and due to historical reasons), code for the serlo editor lives in many places:

* https://github.com/edtr-io
* https://github.com/serlo/frontend/tree/staging/src/edtr-io
* https://github.com/serlo/ece-as-a-service (RLP)

We need to find a way to consolidate all code in one repository github.com/serlo/serlo-editor

## acceptance criteria

- [ ] No duplicate code
- [ ] We can start working on the UX/UI improvements


## Minimal TODOs for archiving the acceptance criteria

- [x] #39
- [x] Make a plan for consolidating all code
- [x] Check ToDos with all developers working on this issue
- [x] #93
- [ ] #94 (blocked by DB-migrations)
- [x] #95
- [x] Question: One package per plugin or one package with all plugins? -> targets the new plugins (duplication for mono-repo question)
- [ ] #99
- [x] #97 
- [ ] Add “box”, “equations”, “table” into edtr-io
- [ ] Add tailwind to edtr-io
- [ ] Publish text-plugin with Slate-upgrade as alpha to NPM (to learn how it will work)
- [ ] How can we test changes in the editor in the future?! 
- [ ] Publish “box”, “equations”, “table” to NPM
- [ ] Use new plugins of NPM in “frontend” and “ece-as-a-service” (RLP integration)

## Follow-Ups

Those things need also be done but we can start working on UX/UI aleady

- [ ] Move repositories from “edtr-io” to “serlo” organization
- [ ] Archive “edtr-io” packages + repositories + website
- [ ] Consider moving from mono-repo to single bundle
- [ ] Question: How to have small bundle in viewing mode? (tree-shaking)
- [ ] Question: What shall be the JavaScript API in the future?!
- [ ] Move all plugins from frontend + ece-as-a-service to serlo-editor
- [ ] Move “ece-as-a-service” into “serlo-editor”
- [ ] Once the [database migration](https://github.com/serlo/documentation/issues/4) has been done, rename serlo-table to table

</details>

**Comment by kulla** [comment]
Is done
