### ISSUE TITLE
Use ESM in each repository which uses JavaScript

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#197]
There is currently a transition from CommonJS to the ESM format (see https://blog.logrocket.com/commonjs-vs-es-modules-node-js/). We don't use ESM consistent in each repository.

### When is a repo sucessfully using ESM?

In `package.json` you should add `type: "module"` as in https://github.com/serlo/serlo-editor-for-edusharing/blob/main/package.json#L11 and make all the necessary changes so that everything works (CI / Tests / Docker image). That's a lot of work! See https://github.com/serlo/serlo-editor-for-edusharing/pull/103 for an example PR doing it. Have a Pair programming session when @kulla or @hugotiburtino before you start doing it.

### List of repositories / ToDos

- [x] https://github.com/serlo/database-layer
- [x] https://github.com/serlo/backlog/issues/256
- [x] https://github.com/serlo/cloudflare-worker/issues/356
- ~https://github.com/serlo/frontend~
- [x] serlo/frontend-e2e-tests#41
- [x] serlo/db-migrations#66
- [x] serlo/notification-mail-service#67
- [x] https://github.com/serlo/serlo-editor-for-edusharing

## Resources

* https://dev.to/jldec/migrating-from-commonjs-to-esm-2p24
* [ESM in Node.JS](https://nodejs.org/api/esm.html)
* [ESM with ts-node](https://www.npmjs.com/package/ts-node#commonjs-vs-native-ecmascript-modules)
* [Usage of ESM in Jest](https://github.com/serlo/cloudflare-worker/issues/356)
