### ISSUE TITLE
Update Node.JS to 18.X

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#198]
The most current LTS version of Node.JS is 18.x and we should make sure that we use it in all repositories, see https://nodejs.dev/en/about/releases/

## what needs to be done?

https://github.com/serlo/documentation/wiki/How-Tos#how-to-update-the-version-of-nodejs--rust--python

## Todos

- [x] serlo/database-layer#466
- [x] https://github.com/serlo/notification-mail-service
- [x] https://github.com/serlo/api.serlo.org
- [x] https://github.com/serlo/cloudflare-worker
- [x] https://github.com/serlo/frontend
- [x] https://github.com/serlo/frontend-e2e-tests
- [x] https://github.com/serlo/db-migrations
- [x] https://github.com/serlo/serlo-editor-for-edusharing
