### ISSUE TITLE
Update yarn to most current version in all major repositories

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#200]
See https://yarnpkg.com/cli/set/version. Todo-List:

- [x] serlo/database-layer#462
- [x] https://github.com/serlo/api.serlo.org/issues/815
- [x] https://github.com/serlo/cloudflare-worker/issues/391
- [x] serlo/notification-mail-service#57
- [x] serlo/frontend#2560
- [x] serlo/frontend-e2e-tests#34
- [x] serlo/serlo-editor-for-edusharing#279

**Comment by eliflores** [comment]
// Re-opened to circle back on using `yarn` as a package manager in https://github.com/serlo/frontend-e2e-tests =)
