### ISSUE TITLE
Add / check proper yarn setting in all repositories

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#202]
Things to check:

* Is https://github.com/serlo/serlo-editor-for-edusharing/blob/5e10dc9da32fed7d23cadd721511b8488f8b9bad/.yarnrc.yml#L7-L14 present?
* Is https://github.com/serlo/serlo-editor-for-edusharing/blob/5e10dc9da32fed7d23cadd721511b8488f8b9bad/.gitignore#L34-L41 present in `.gitignore`?
* Is https://github.com/serlo/serlo-editor-for-edusharing/blob/5e10dc9da32fed7d23cadd721511b8488f8b9bad/package.json#L142 present?

## repositories

- [x] serlo/database-layer#510
- [x] serlo/api.serlo.org#949
- [x] serlo/cloudflare-worker#447
- [x] https://github.com/serlo/frontend
- [x] serlo/frontend-e2e-tests#35
- [x] serlo/db-migrations#67
- [x] https://github.com/serlo/serlo-editor-for-edusharing
- [x] serlo/notification-mail-service#69

**Comment by eliflores** [comment]
Done 💚
