### ISSUE TITLE
Pin used version of Rust / Node.JS / python / yarn via `.tool-versions`

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#203]
See https://asdf-vm.com/manage/configuration.html#tool-versions

## Blocker

- [x] serlo/backlog#198 
- [x] serlo/backlog#200 
- [x] https://github.com/serlo/database-layer/issues/460

## Afterwards

Inform all developers that they might need to update their tools and how they can do it

## List of repositories

- [x] Pin tools in https://github.com/serlo/database-layer
- [x] serlo/api.serlo.org#946
- [x] serlo/cloudflare-worker#424
- ~Pin tools in https://github.com/serlo/frontend~
- ~Pin tools in https://github.com/serlo/frontend-e2e-tests~
- [x] serlo/db-migrations#56
- [x] Pin tools in https://github.com/serlo/serlo-editor-for-edusharing (it was already added ✅ )
- [x] serlo/notification-mail-service#64
