### ISSUE TITLE
Add merge queue for all repositories which shall get the dependabot

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#205]
See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue, note that https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions need to be done (example: https://github.com/serlo/api.serlo.org/pull/910).

## Blocker

- [x] https://github.com/serlo/backlog/issues/213

## Todo-List

- [x] Enable merge queue for https://github.com/serlo/database-layer
- [x] Enable merge queue for https://github.com/serlo/api.serlo.org
- [x] Enable merge queue for https://github.com/serlo/cloudflare-worker
- ~https://github.com/serlo/frontend~
- ~Enable merge queue for https://github.com/serlo/frontend-e2e-tests~
- [x] Enable merge queue for https://github.com/serlo/db-migrations
- ~Enable merge queue for https://github.com/serlo/serlo-editor-for-edusharing~
- [x] Enable merge queue for https://github.com/serlo/notification-mail-service

**Comment by kulla** [comment]
Done
