### ISSUE TITLE
Add merge_group trigger in all repositories where the merge queue shall be enabled

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#212]
See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

## Todo-List

- [x] Add `merge_group` trigger for https://github.com/serlo/database-layer
- [x] https://github.com/serlo/api.serlo.org
- [x] #213
- ~https://github.com/serlo/frontend~
- ~Add `merge_group` trigger for https://github.com/serlo/frontend-e2e-tests~
- [x] Add `merge_group` trigger for https://github.com/serlo/db-migrations
- ~Add `merge_group` trigger for https://github.com/serlo/serlo-editor-for-edusharing~
- [x] Add `merge_group` trigger for https://github.com/serlo/notification-mail-service

**Comment by eliflores** [comment]
All the repositories where merge queue will / is enabled have `merge_group` in the GitHub Actions workflows ✨
