### ISSUE TITLE
Add proper automated testing

### ISSUE THREAD

**Issue by sesa929** [serlo/backlog#24]
Currently we only have tests for main components which are easily testable (like the `store` component). Tests for React components are missing. Maybe we also want to introduce other unit tests for some subcomponents.

## TODOs
- [ ] which tests? (unit, components, end-to-end)
- [ ] which test-frameworks?
- [x] automated tests for box plugin
- [x] automated tests for text plugin
- [ ] automated tests for all other plugins
- [ ] automated tests for seetings
- [ ] automated tests for plugin toolbar
- [ ] automated tests for ...?
