### ISSUE TITLE
☂️ Umbrella issue: Refactorings: user management 

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/backlog#310]
- [x] Refactorings in oauth mutations, see https://github.com/serlo/api.serlo.org/pull/694#discussion_r1065802837 and https://github.com/serlo/api.serlo.org/pull/694#discussion_r1065803070
- [x] session is a user input and thus need to be checked / or the GraphQL types need to be updated (https://github.com/serlo/api.serlo.org/pull/694#discussion_r1065801847)
- [ ] Add test for OAuth mutations OR make kratos communicate directly with hydra, removing from here the oauth code 
- [ ] Refactor SessionDecoder and IdentityDecoder
- [ ] Use io-ts check here (https://github.com/serlo/api.serlo.org/pull/694#discussion_r1062321792) and in general find a better way of generating the identity interface (maybe getting from json schema using codegen)

Actually, there are a lot of decisions to be made. This issue may be splitted into serveral ones.
