### ISSUE TITLE
Investigate in a prototype whether template elements in Slate are possible

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#84]
Slate has the mental model of a content that content is a list of lists whose elements can have attributes. Screenshot from the meeting as a reminder: 
![2023-02-16-154845_800x766_scrot](https://user-images.githubusercontent.com/1327215/219397888-ea040ade-c129-4881-9a96-0fbfee9cf9fe.png)

Thus it does not support template elements which we would represent as an object in json. For example an exercise we would represent as:

```js
const exercise {
  "exerciseContent": ...,
  "answer": ...
}
```

We need to investigate in a prototype whether there is a workaround for having such content in slate (for example by overriding normalization: https://docs.slatejs.org/concepts/11-normalizing ). This prototype can include:

* some rich text
* an exercise element with exercise and answer
* an article plugin with `main` content and a link section

Prototype repo: https://github.com/AsterMiha/slate-editor-tests

## TODO

- [x] Add Slate Example repositories
- [x] Try to add an exercise template to it as a block element
- [ ] Create exercise template into a new React project

## Useful information

* https://docs.google.com/presentation/d/1gww-KXR9VB8ujCGBGKSP4fgfyl-cqKww1-1b5PyxxN0/edit#slide=id.g195117afa8d_17_75
* https://docs.slatejs.org/
* https://github.com/serlo/documentation/wiki/Content-format -> Here are the current plugins explained we use
* Try out our editor in test enviornment
